---
apiVersion: v1
kind: Namespace
metadata:
  name: clusterset-privileged
  labels:
    name: clusterset-privileged
---
apiVersion: k3k.io/v1alpha1
kind: ClusterSet
metadata:
  name: clusterset-privileged
  namespace: clusterset-privileged
spec:
  disableNetworkPolicy: false
  allowedNodeTypes:
  - "shared"
  - "virtual"
  podSecurityAdmissionLevel: "privileged"
---
apiVersion: v1
kind: Pod
metadata:
  name: security-context-privileged
  namespace: clusterset-privileged
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups: [4000]
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: clusterset-baseline
  labels:
    name: clusterset-baseline
---
apiVersion: k3k.io/v1alpha1
kind: ClusterSet
metadata:
  name: clusterset-baseline
  namespace: clusterset-baseline
spec:
  disableNetworkPolicy: false
  allowedNodeTypes:
  - "shared"
  - "virtual"
  podSecurityAdmissionLevel: "baseline"
---
apiVersion: v1
kind: Pod
metadata:
  name: security-context-baseline
  namespace: clusterset-baseline
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups: [4000]
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: clusterset-restricted
  labels:
    name: clusterset-restricted
---
apiVersion: k3k.io/v1alpha1
kind: ClusterSet
metadata:
  name: clusterset-restricted
  namespace: clusterset-restricted
spec:
  disableNetworkPolicy: false
  allowedNodeTypes:
  - "shared"
  - "virtual"
  podSecurityAdmissionLevel: "restricted"
---
apiVersion: v1
kind: Pod
metadata:
  name: security-context-restricted
  namespace: clusterset-restricted
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups: [4000]
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
