#cloud-config
package_update: true
package_upgrade: true

runcmd:
  - sudo mkdir -p /etc/rancher/k3s/
  - wget --quiet -D - https://github.com/k3s-io/kine/releases/download/v0.11.7/kine-amd64
  - chmod +x kine-amd64
  - sudo mv kine-amd64 /usr/local/bin/
  - wget --quiet -D - https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v2.4.1/clusterawsadm-linux-amd64
  - chmod +x clusterawsadm-linux-amd64
  - sudo cp ./clusterawsadm-linux-amd64 /usr/local/bin/clusterawsadm
  - wget --quiet -D - https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.6.1/clusterctl-linux-amd64
  - mv clusterctl-linux-amd64 /usr/local/bin/cctl
  - chmod +x /usr/local/bin/cctl
  - wget --quiet -D - https://github.com/rancher/k3k/releases/download/v0.2.1/k3k
  - chmod +x k3k
  - mv k3k /usr/local/bin/
  - wget https://github.com/rancher/k3k/releases/download/v0.2.1/k3kcli
  - chmod +x k3kcli
  - mv k3kcli /usr/local/bin/

  