#cloud-config
# this bootstraps postgresql database for k3s/rke2 to use as an external datastore
package_update: true
package_upgrade: true
packages:
  - wget
  - curl

runcmd:
  - wget --quiet -D - https://dev.mysql.com/get/mysql84-community-release-sl15-1.noarch.rpm
  - sudo rpm -Uvh mysql84-community-release-sl15-1.noarch.rpm
  - sudo zypper -n modifyrepo -e mysql-8.4-lts-community
  - sudo zypper -n refresh
  - sudo zypper -n install mysql-community-server
  - echo "bind-address=0.0.0.0 " >> /etc/my.cnf
  - echo "mysql_native_password=ON " >> /etc/my.cnf
  - sudo mysqld --validate-config --log_error_verbosity=9
  - systemctl enable --now mysql
  - /usr/bin/mysql -u root -e "CREATE DATABASE k3s"
  - /usr/bin/mysql -u root -e "CREATE USER 'k3s'@'%' IDENTIFIED BY 'YOUR_PASSWORD_HERE'"
  - /usr/bin/mysql -u root -e "GRANT ALL PRIVILEGES ON k3s.* TO 'k3s'@'%'"
  - systemctl restart mysql
  
