#cloud-config
# this bootstraps postgresql database for k3s/rke2 to use as an external datastore
package_update: true
package_upgrade: true

runcmd:
  - sudo mkdir -p /etc/postgresql/16/main/conf.d
  - sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add - ;
  - sudo apt update
  - sudo apt install postgresql-16 -y
  - systemctl enable --now postgresql
  - sudo touch /etc/postgresql/16/main/conf.d/postgresql.conf
  - echo "host    all    all    0.0.0.0/0    md5" >> /etc/postgresql/16/main/pg_hba.conf
  - echo "listen_addresses = '*'" >> /etc/postgresql/16/main/postgresql.conf
  - echo "port = 5432" >> /etc/postgresql/16/main/postgresql.conf
  - systemctl restart postgresql
  - sudo --user=postgres -- psql -c "CREATE ROLE k3s WITH PASSWORD 'YOUR_PASSWORD_HERE';"
  - sudo --user=postgres -- psql -c "CREATE DATABASE k3s WITH OWNER = k3s ;"
  - sudo --user=postgres -- psql -c "GRANT ALL ON DATABASE k3s TO k3s;"
  - sudo --user=postgres -- psql -c "ALTER ROLE k3s WITH SUPERUSER CREATEDB LOGIN CREATEROLE REPLICATION BYPASSRLS;"
  - wget --quiet -D - https://github.com/k3s-io/kine/releases/download/v0.11.7/kine-amd64
  - chmod +x kine-amd64
  - sudo mv kine-amd64 /usr/local/bin/
  
# write_files: #consider writing a local script to send a database copy to s3 bucket?
#   - path: /etc/postgresql/15/main/conf.d/postgresql.conf
#     permissions: '0644'
#     owner: postgres:postgres
#     content: | 
#       data_directory = '/var/lib/postgresql/15/main'
#       hba_file = '/etc/postgresql/15/main/pg_hba.conf'
#       ident_file = '/etc/postgresql/15/main/pg_ident.conf'
#       external_pid_file = '/var/run/postgresql/15-main.pid'
#       port = 5432                             # (change requires restart)
#       max_connections = 100                   # (change requires restart)
#       unix_socket_directories = '/var/run/postgresql'
#       ssl = on
#       ssl_cert_file = '/etc/ssl/certs/ssl-cert-snakeoil.pem'
#       ssl_key_file = '/etc/ssl/private/ssl-cert-snakeoil.key'
#       shared_buffers = 128MB
#       dynamic_shared_memory_type = posix
#       max_wal_size = 1GB
#       min_wal_size = 80MB
#       log_line_prefix = '%m [%p] %q%u@%d '
#       log_timezone = 'America/Los_Angeles'
#       cluster_name = '15/main'
#       datestyle = 'iso, mdy'
#       timezone = 'America/Los_Angeles'
#       lc_messages = 'C.UTF-8'                 # locale for system error message
#       lc_monetary = 'C.UTF-8'                 # locale for monetary formatting
#       lc_numeric = 'C.UTF-8'                  # locale for number formatting
#       lc_time = 'C.UTF-8'   
#       default_text_search_config = 'pg_catalog.english'
#       include_dir = 'conf.d'
#       listen_addresses = '*'

#   - path: /etc/postgresql/15/main/pg_hba.conf
#     permissions: '0700'
#     owner: postgres:postgres
#     content: | 
#       host    all    all    0.0.0.0/0    md5
